#dubbo conf
dubbo:
  application:
    name: e3-manager-web
  registry:
      address: zookeeper://192.168.223.128:2181
#picture upload conf
spring:
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
#tomcat conf
server:
  port: 8081
