#tomcat conf
server:
  port: 8084
#dubbo conf
dubbo:
  application:
    name: e3-item-web
  registry:
      address: zookeeper://192.168.223.128:2181
# activemq conf
spring:
  activemq:
      user: admin
      password: admin
      broker-url: tcp://192.168.223.128:61616
      pool:
        enabled: true
        max-connections: 50
      packages:
        trust-all: false